"""Add stock to product

Revision ID: 790465feac5c
Revises: 7f3d5cb2cbe4
Create Date: 2025-06-03 04:21:04.843500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790465feac5c'
down_revision = '7f3d5cb2cbe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('stock')

    # ### end Alembic commands ###
